[project]
name = "connectomebench"
description = "Native benchmarking environment for ConnectomeBench + NEURD"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.12.*"
uv = ">=0.4.28"
pip = "*"
cmake = "*"
ninja = "*"
pkg-config = "*"
pymeshlab = "*"
cgal-cpp = "*"
embree = "*"
eigen = "*"
libglu = "*"
mesalib = "*"
libglvnd = "*"
xorg-libx11 = "*"
xorg-libxrender = "*"
xorg-libxext = "*"
xorg-libsm = "*"
xorg-libice = "*"
xorg-libxi = "*"
libxcb = "*"
xorg-libxrandr = "*"
xorg-libxshmfence = "*"
xorg-libxdamage = "*"
xorg-libxfixes = "*"
ffmpeg = "*"
wget = "*"
zip = "*"

[tasks.uv-sync-neurd]
cmd = ["uv", "--project", "envs/neurd", "sync", "--python", "3.8"]
env = { SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL = "true" }

[tasks.neurd-tests]
cmd = ["uv", "--project", "envs/neurd", "run", "python", "-m", "unittest", "discover", "-s", "external/NEURD/tests/unit"]
env = { SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL = "true" }
